"""initial domain schema"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "28f4d3f30347"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_state",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "leads",
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("intake_key", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("company", sa.String(length=160), nullable=True),
        sa.Column("original_message", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("utm", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_status", sa.String(length=24), nullable=False),
        sa.Column("sales_stage", sa.String(length=24), nullable=False),
        sa.Column("temperature", sa.String(length=8), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("analysis_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("priority_override", sa.String(length=8), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("communication_state", sa.String(length=24), nullable=False),
        sa.Column("followup_status", sa.String(length=24), nullable=False),
        sa.Column("followup_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("communication_state IN ('allowed','paused','opted_out')"),
        sa.CheckConstraint(
            "processing_status IN ('pending','processing','completed','needs_review','failed')"
        ),
        sa.CheckConstraint(
            "sales_stage IN ('new','contacted','replied','meeting_booked','won','lost')"
        ),
        sa.CheckConstraint("temperature IS NULL OR temperature IN ('HOT','WARM','COLD')"),
        sa.CheckConstraint("score IS NULL OR (score >= 0 AND score <= 100)"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intake_key"),
        sa.UniqueConstraint("reference"),
    )
    op.create_index(op.f("ix_leads_email"), "leads", ["email"], unique=False)
    op.create_index(
        "ix_leads_followup", "leads", ["followup_status", "followup_due_at"], unique=False
    )
    op.create_index("ix_leads_list", "leads", ["created_at", "id"], unique=False)
    op.create_table(
        "operators",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "rate_limit_buckets",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_rate_limit_buckets_expires_at"), "rate_limit_buckets", ["expires_at"], unique=False
    )
    op.create_table(
        "recipient_suppressions",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_table(
        "analyses",
        sa.Column("lead_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("operation_key", sa.String(length=140), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_version", sa.String(length=80), nullable=False),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_key"),
    )
    op.create_index(op.f("ix_analyses_lead_id"), "analyses", ["lead_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("lead_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_lead_id"), "audit_events", ["lead_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("lead_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("purpose_key", sa.String(length=180), nullable=False),
        sa.Column("current_version_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("approved_version_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("rfc_message_id", sa.String(length=512), nullable=True),
        sa.Column("reply_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("send_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parent_message_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("direction IN ('inbound','outbound')"),
        sa.CheckConstraint(
            "state IN ('draft','pending_approval','approved','queued','sending','provider_accepted','rejected','cancelled','failed','delivery_unknown','received','unmatched')"
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("purpose_key"),
    )
    op.create_index(op.f("ix_messages_lead_id"), "messages", ["lead_id"], unique=False)
    op.create_index(
        op.f("ix_messages_rfc_message_id"), "messages", ["rfc_message_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("operator_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["operators.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("lead_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("message_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("dedup_key", sa.String(length=180), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedup_key"),
    )
    op.create_index("ix_jobs_due", "jobs", ["status", "next_attempt_at"], unique=False)
    op.create_table(
        "message_versions",
        sa.Column("message_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=250), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "revision"),
    )
    op.create_table(
        "approval_decisions",
        sa.Column("version_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("operator_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("decision", sa.String(length=12), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("decision IN ('approve','reject')"),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.id"],
        ),
        sa.ForeignKeyConstraint(["version_id"], ["message_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "job_steps",
        sa.Column("job_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("step", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("claim_token", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("reserved_tokens", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('not_started','running','completed','unknown','retryable','failed')"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "generation", "step"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_steps")
    op.drop_table("approval_decisions")
    op.drop_table("message_versions")
    op.drop_index("ix_jobs_due", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_messages_rfc_message_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_lead_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_audit_events_lead_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_analyses_lead_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_table("recipient_suppressions")
    op.drop_index(op.f("ix_rate_limit_buckets_expires_at"), table_name="rate_limit_buckets")
    op.drop_table("rate_limit_buckets")
    op.drop_table("operators")
    op.drop_index("ix_leads_list", table_name="leads")
    op.drop_index("ix_leads_followup", table_name="leads")
    op.drop_index(op.f("ix_leads_email"), table_name="leads")
    op.drop_table("leads")
    op.drop_table("integration_state")
    # ### end Alembic commands ###
