"""enforce current analysis and version references"""

from alembic import op

revision = "2e5d18b9d019"
down_revision = "28f4d3f30347"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_lead_analysis",
        "leads",
        "analyses",
        ["analysis_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_message_approved_version",
        "messages",
        "message_versions",
        ["approved_version_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_message_current_version",
        "messages",
        "message_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_message_current_version", "messages", type_="foreignkey")
    op.drop_constraint("fk_message_approved_version", "messages", type_="foreignkey")
    op.drop_constraint("fk_lead_analysis", "leads", type_="foreignkey")
    # ### end Alembic commands ###
