"""bind analysis and message versions to owners"""

from alembic import op

revision = "31d9d4323a5f"
down_revision = "2e5d18b9d019"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_analysis_owner", "analyses", ["lead_id", "id"])
    op.drop_constraint(op.f("fk_lead_analysis"), "leads", type_="foreignkey")
    op.create_foreign_key(
        "fk_lead_owned_analysis",
        "leads",
        "analyses",
        ["id", "analysis_id"],
        ["lead_id", "id"],
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    op.create_unique_constraint("uq_version_owner", "message_versions", ["message_id", "id"])
    op.drop_constraint(op.f("fk_message_current_version"), "messages", type_="foreignkey")
    op.drop_constraint(op.f("fk_message_approved_version"), "messages", type_="foreignkey")
    op.create_foreign_key(
        "fk_message_owned_approval",
        "messages",
        "message_versions",
        ["id", "approved_version_id"],
        ["message_id", "id"],
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_message_owned_current",
        "messages",
        "message_versions",
        ["id", "current_version_id"],
        ["message_id", "id"],
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_message_owned_current", "messages", type_="foreignkey")
    op.drop_constraint("fk_message_owned_approval", "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_message_approved_version"),
        "messages",
        "message_versions",
        ["approved_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_message_current_version"),
        "messages",
        "message_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("uq_version_owner", "message_versions", type_="unique")
    op.drop_constraint("fk_lead_owned_analysis", "leads", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_lead_analysis"), "leads", "analyses", ["analysis_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint("uq_analysis_owner", "analyses", type_="unique")
    # ### end Alembic commands ###
